name: Go

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j:5
        ports:
          - 7687:7687
        env:
          # test only
          NEO4J_AUTH: neo4j/williamfzc
    steps:
      - uses: actions/checkout@v3
        with:
          # at least support HEAD~1 for testing
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up TiKV
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
          source /home/runner/.profile
          tiup playground --mode tikv-slim &

      - name: Build
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          make

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -coverpkg=./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
