name: perftest

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          make

      - name: Prepare third party repos
        run: |
          # java
          git clone --depth=1 https://github.com/spring-projects/spring-boot.git
          # golang
          git clone --depth=1 https://github.com/gin-gonic/gin.git

      - name: Test In Offline
        run: |
          ./sibyl upload --src ./spring-boot --withCtx --dry
          ./sibyl upload --src ./gin --withCtx --dry
