name: perftest

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j:5
        ports:
          - 7687:7687
        env:
          # test only
          NEO4J_AUTH: neo4j/williamfzc
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          make

      - name: Prepare third party repos
        run: |
          # java
          git clone --depth=1 https://github.com/google/guava.git
          git clone --depth=1 https://github.com/antlr/antlr4.git
          # golang
          git clone --depth=1 https://github.com/gin-gonic/gin.git
          git clone --depth=1 https://github.com/spf13/cobra.git

      - name: Execute
        run: |
          ./sibyl server --uri bolt://localhost:7687 --user neo4j --pwd williamfzc &
          sleep 2
          ./sibyl upload --src ./guava --withCtx --batch 50
          ./sibyl upload --src ./antlr4 --withCtx --batch 50
          ./sibyl upload --src ./gin --withCtx --batch 50
          ./sibyl upload --src ./cobra --withCtx --batch 50
        env:
          GIN_MODE: release
