name: perftest

on:
  push:
    tags:
      - 'v*'
      - 'perf*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.7
          make

      - name: Start Sibyl
        run: |
          chmod +x ./sibyl
          ./sibyl server &

      - name: Prepare third party repos
        run: |
          # java
          git clone --depth=1 https://github.com/spring-projects/spring-boot.git
          git clone --depth=1 https://github.com/jacoco/jacoco.git
          # golang
          git clone --depth=1 https://github.com/gin-gonic/gin.git
          git clone --depth=1 https://github.com/spf13/cobra
          # python
          git clone --depth=1 https://github.com/psf/requests
          git clone --depth=1 https://github.com/tiangolo/fastapi.git
          # kotlin
          git clone --depth=1 https://github.com/square/okhttp
          # javascript
          git clone --depth=1 https://github.com/axios/axios.git

      - name: Test Java
        run: |
          ./sibyl upload --src ./spring-boot
          ./sibyl upload --src ./jacoco

      - name: Test Golang
        run: |
          ./sibyl upload --src ./gin
          ./sibyl upload --src ./cobra

      - name: Test Python
        run: |
          ./sibyl upload --src ./requests
          ./sibyl upload --src ./fastapi

      - name: Test Kotlin
        run: |
          ./sibyl upload --src ./okhttp

      - name: Test JavaScript
        run: |
          ./sibyl upload --src ./axios
